---
title: "Takım: R_amam_soRmam_biR_daha"
sidebar: false 
---

Bu sayfa ile İş Analitiği çalışmalarımızı paylaşıyoruz. Takım Üyelerimize ve proje özetimize aşağıdan erişebilir, çalışmalarımızı daha detaylı incelemek için sayfanın tepesinde bulunan araç çubuğundan faydalanabilirsiniz.

Lütfen faaliyetlerimizi görmek için bizi takipte kalın.

## Takım Üyeleri

1.  [Yasmin Yağmur KARSLI](/takim/yasmin.qmd)
2.  [Erdi YAŞAR](/takim/erdi.qmd)
3.  [Fikret Emin SEVGİLİ](/takim/fikret.qmd)
4.  [Zahide CANSIZ FIRAT](/takim/zahide.qmd)
5.  [Buse Nur YAŞAR](/takim/buse.qmd)
6.  [Alperen SEÇKİNOĞULLARI](/takim/alperen.qmd)

## Proje Adı

MUY660-???? Analiti??i iyile??tirme ??al????malar?? (??rnek)

## Proje Konusu

??rnek: Bu projede MUY660-???? Analiti??i ders i??eri??inin analitik yakla????mlarla iyile??tirilmesini hedefledik. Bu do??rultuda t??m ??niversitelerdeki benzer derslerin verisini toplayarak bir veri seti olu??turduk Analiz i??in ??????.. y??ntemleri kullanarak, ??????. ??al????malar?? yapt??k Sonu?? olarak, MUY660-???? Analiti??i dersinin d??nyadaki t??m derslerden daha iyi oldu??unu ve bu dersi ald??????m??z i??in ??ok mutlu oldu??umuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar

Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile ??arp??c?? sonu??lar sunulmal??d??r.
