---
title: "Proje Adı"
format: html
number-sections: true
---

**Proje sayfamıza hoş geldiniz.**

*Projemizle ilgili güncellemelerden haberdar olmak için bu alanı takip edin.*

(Aşağıdaki başlıklar örnek olarak verilmiştir; lütfen gerektiği şekilde düzenlemekten çekinmeyin.)

# Proje Genel Bakış ve Kapsamı

xxxxxx

# Veri

xxxxxx

## Veri Kaynağı

xxxxxx

## Veri Hakkında Genel Bilgiler

xxxxxx

## Tercih Sebebi

xxxxxx

## Ön İşleme


install.packages("readxl") 
install.packages("dplyr")
install.packages("ggplot2")
install.packages("tidyr") 
install.packages("kableExtra") 
install.packages("openxlsx") 
install.packages(c("stringr", "scales", "plotly", "ggrepel", "ggthemes","patchwork"))
install.packages("plotrix")
install.packages("janitor")

library(patchwork)
library(readxl) 
library(openxlsx) 
library(dplyr)
library(ggplot2) 
library(tidyr) 
library(stringr) 
library(scales) 
library(plotly)
library(ggrepel) 
library(ggthemes)
library(kableExtra)


# Analiz

turkiye_geneli <- read_excel("veri/turkiye_geneli.xlsx")
head(turkiye_geneli)
Kadin_Erkek_Yas_Dagilimlari <- read_excel("veri/Kadin_Erkek_Yas_Dagilimlari.xlsx")
head(Kadin_Erkek_Yas_Dagilimlari)
evlilik_suresi<- read_excel("veri/Evlilik_suresi_Turkiye_geneli.xlsx")
head(evlilik_suresi)

# erdi yasmin Evlilik süresine göre boşanma sayısı grafiği
#ortalama_evlilik_suresi_bazli<-apply(evlilik_suresi,2,mean)

yildan_az_1<-sum(evlilik_suresi[2])
yil_1_5<-sum(evlilik_suresi[3:7])
yil_6_10<-sum(evlilik_suresi[8:12])
yil_11_15<-sum(evlilik_suresi[13:17])
yil_16_20<-sum(evlilik_suresi[18:22])
bosanma_sayisi <- data.frame(
  Evlilik_Suresi = c("0-1 yıldan az", "1-5 yıl", "6-10 yıl", "11-15 yıl", "16-20+ yıl"),
  total_bosanma_sayisi<-c(yildan_az_1,yil_1_5,yil_6_10,yil_11_15,yil_16_20)
)
bosanma_sayisi$Evlilik_Suresi <- factor(
  bosanma_sayisi$Evlilik_Suresi,
  levels = c("0-1 yıldan az", "1-5 yıl", "6-10 yıl", "11-15 yıl", "16-20+ yıl")
)
print(bosanma_sayisi)
bosanma_sayisi|> ggplot(aes(x=Evlilik_Suresi, y=total_bosanma_sayisi)) + geom_bar(stat = "identity", fill = "skyblue",width = 0.5)+
geom_text(aes(label = total_bosanma_sayisi), vjust = -0.5, size = 3)+labs(
      title = "Evlilik Suresine Gore Bosanma Sayısı",
    x = "Evlilik Suresi",
    y = "Toplam Boşanma Sayısı"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 12, face = "bold")
  )
#erdi yasmin (sütun sıralasmını levels kodu ile yaptık chatgpt den yardım aldık)

#erdi yasmin (2) (Evlilik süresi ve yıllara göre boşanma sayısının karşılaştırılması)
yillar_0_1<-vector()
for (i in seq(1,24)) 
{yillar_0_1[i]<-sum(evlilik_suresi[i,2])

}
yillar_1_5<-vector()
for (i in seq(1,24)) 
{yillar_1_5[i]<-sum(evlilik_suresi[i,3:7])

}
yillar_6_10<-vector()
for (i in seq(1,24)) 
{yillar_6_10[i]<-sum(evlilik_suresi[i,8:12])

}
yillar_11_15<-vector()
for (i in seq(1,24)) 
{yillar_11_15[i]<-sum(evlilik_suresi[i,13:17])

}

yillar_16_20<-vector()
for (i in seq(1,24)) 
{yillar_16_20[i]<-sum(evlilik_suresi[i,18:22])

}
yillar <-vector()
for(i in seq(1,24))
{yillar[i]<-evlilik_suresi[i,1]}

yillar <- as.numeric (yillar)
yillara_gore_bs <- data.frame(
  'yil_0_1'=yillar_0_1,
  `yil_1_5` = yillar_1_5,
  `yil_6_10` = yillar_6_10,
  `yil_11_15` = yillar_11_15,
  `yil_16_20` = yillar_16_20)

yillara_gore_bs$Yil <- yillar

df_long <- yillara_gore_bs %>% pivot_longer(cols = -Yil, names_to = "Evlilik_Suresi", values_to = "Deger")
  
df_long$Evlilik_Suresi <- factor(df_long$Evlilik_Suresi,
  levels = c("yil_0_1", "yil_1_5", "yil_6_10", "yil_11_15", "yil_16_20")
)

ggplot(df_long,aes(x = Yil, y = Deger, color = Evlilik_Suresi)) +
  geom_line(size = 1.2) + labs(
      title = "Yıllara Gore Bosanma Sayıları",
    x = "Yıllar",
    y = "Toplam Bosanma Sayısı"
  ) + theme_minimal()+
  scale_x_continuous(breaks = seq(min(df_long$Yil), max(df_long$Yil), by = 1))+theme( axis.text.x = element_text(angle = 90, hjust = 1))+theme(plot.title = element_text(hjust = 0.5, size = 12, face = "bold")
  )

Yas_Farki_Turkiye_geneli <- read_excel("veri/Yas_Farki_Turkiye_geneli.xlsx")
head(Yas_Farki_Turkiye_geneli)
#yasmin erdi 3 bölgelere göre erkek kadın boşanma-start

ornek <- read_excel("veri/yasmin-erdi/ornek.xlsx")
ornek$Yil <- as.numeric (ornek$Yil)
str(ornek)


veri_long <- ornek %>% pivot_longer(cols = -c(Kadin_Yas_Grubu, Yil),  names_to = "Bolge", values_to = "Deger")





# 6 yıllık dönemleri tanımlayalım
veri_long <- veri_long %>%
  mutate(Donem = case_when(
    Yil %in% 2001:2006 ~ "2001–2006",
    Yil %in% 2007:2012 ~ "2007–2012",
    Yil %in% 2013:2018 ~ "2013–2018",
    Yil %in% 2019:2024 ~ "2019–2024",
    TRUE ~ NA_character_
  )) %>%
  filter(!is.na(Donem))  # sadece belirli dönemler kalsın

# Grafik çizimi: 4 facet, her biri bir dönem
ggplot(veri_long, aes(x = Deger , y = Kadin_Yas_Grubu, color = Bolge)) +
  geom_point(position = position_jitter(width = 0.1), size = 1, alpha = 1) +
  facet_wrap(~ Donem, ncol = 2) +
  labs(title = "Kadın Yaş Gruplarına Gore Bolgesel Dağılım (2001–2024)",
    x = "Bosanma Sayısı",
    y = "Kadın Yaş Aralığı",
    color = "Bolge") +theme_minimal() +theme(axis.text.x = element_text(angle = 0, hjust = 1))+ scale_x_continuous(limits = c(0, 20000),         
    breaks = seq(0, 20000, 5000))




str(veri_long)

## Keşifsel Veri Analizi

Durum <- c("evlenme_sayisi","bosanma_sayisi")

grafik <- turkiye_geneli |> ggplot() +
  geom_line(aes(x = yil, y = evlenme_sayisi, color = "Evlenme Sayısı",group=1), size = 1.7) +
  geom_line(aes(x = yil, y = bosanma_sayisi, color = "Boşanma Sayısı",group=1), size = 1.7) +
  scale_color_manual(values = c("Evlenme Sayısı" = "blue", "Boşanma Sayısı" = "red")) +
  scale_y_continuous(breaks = seq(0, 700000, by = 50000), labels = comma) +
  labs(
    title = "Türkiye'de Yıllara Göre Evlenme ve Boşanma Sayıları",
    x = "Yıl",
    y = "Kişi Sayısı",
    color = "Durum") +
  theme( axis.text.x = element_text(angle = 90, hjust = 1))

grafik


## Trend Analizi
Sys.setlocale("LC_ALL", "Turkish")

#Kadın Yaş Dağılımları Yıllara göre#


# Veriyi oku
df_kadin <- read_excel("veri/Kadin_Erkek_Yas_Dagilimlari_Turkiye.xlsx", sheet = "Kadın Yaş Dağılımı")

# Kolon adını düzelt (boşluk içeriyor)
colnames(df_kadin)[3] <- "Bosanan_Kadin_Sayisi"

# Barplot çizimi
ggplot(df_kadin, aes(x = as.factor(Yil), y = Bosanan_Kadin_Sayisi, fill = Yas_Grubu)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "Türkiye'de Boşanan Kadın Yaş Dağılımı", x = "Yıl", y = "Boşanan Kadın Sayısı") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
#Kadın Yaş Dağılımları Yıllara göre Bitiş#

##Erkek Yaş Dağılımları Yıllara göre#

# Veriyi oku
df_erkek <- read_excel("veri/Kadin_Erkek_Yas_Dagilimlari_Turkiye.xlsx", sheet = "Erkek Yaş Dağılımı")

# Kolon adını düzelt (boşluk içeriyor)
colnames(df_erkek)[3] <- "Bosanan_Erkek_Sayisi"

# Barplot çizimi
ggplot(df_erkek, aes(x = as.factor(Yil), y = Bosanan_Erkek_Sayisi, fill = Yas_Grubu)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_minimal() +
  labs(title = "Türkiye'de Boşanan Erkek Yaş Dağılımı", x = "Yıl", y = "Boşanan Erkek Sayısı") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
#Erkek Yaş Dağılımları Yıllara göre Bitiş#


# Daire grafikleri

library(readxl)
library(RColorBrewer)

# Veriyi oku
df <- read_excel("veri/Kadin_Erkek_Yas_Dagilimlari_Turkiye Genelll.xlsx")

# Kadın ve erkek verisi
kadin_veri <- df$Turkiye_Kadin_Dagilim
erkek_veri <- df$Turkiye_Erkek_Dagilim
yas_gruplari <- df$Yas_Grubu

# Yüzdeleri hesapla
kadin_yuzde <- round(kadin_veri / sum(kadin_veri) * 100, 1)
erkek_yuzde <- round(erkek_veri / sum(erkek_veri) * 100, 1)

# Etiketleri oluştur
kadin_etiketler <- paste0(yas_gruplari, "\n", kadin_yuzde, "%")
erkek_etiketler <- paste0(yas_gruplari, "\n", erkek_yuzde, "%")

# PASTEL renk paleti (4 yaş grubu için)
renkler <- brewer.pal(n = 4, name = "Pastel1")  # Alternatif: "Set3"

# Grafik ekranını ikiye böl
par(mfrow = c(1, 2))

# Kadın grafiği
pie(kadin_veri, labels = kadin_etiketler, main = "Boşanma Yaş Dağılımı (Kadın)", col = renkler,font=2,cex=0.5)


# Erkek grafiği
pie(erkek_veri, labels = erkek_etiketler, main = "Boşanma Yaş Dağılımı (Erkek)", col = renkler,font=2,cex=0.5)
#
#PieChart Bitiş



## Trend Analizi
library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)

# Veriyi oku
evlilik_bosanma_hiz <- read_excel("veri/evlilik-bosanma-nufus.xls")

# Kaba evlenme hızı hesapla
evlilik_bosanma_hiz <- evlilik_bosanma_hiz %>%
  mutate(
    Yil = as.numeric(Yil),
    Kaba_Evlenme_Hizi = (Evlenme_Sayisi / Nufus_Sayisi) * 1000
  )

# Çizgi verisi hazırlığı
hizlar <- evlilik_bosanma_hiz %>%
  select(Yil, Kaba_Evlenme_Hizi) %>%
  pivot_longer(cols = Kaba_Evlenme_Hizi, names_to = "Kaba_Evlenme_Hizi", values_to = "Deger") %>%
  mutate(
    Kaba_Evlenme_Hizi = "Kaba evlenme hızı",  # legend için etiket
    Etiket = paste0(format(round(Deger, 2), nsmall = 2), " "),
    Y_Pos = Deger * 80000
  )

# Barplot çizelim
ggplot() +
  geom_bar(data = evlilik_bosanma_hiz,
           aes(x = Yil, y = Evlenme_Sayisi),
           stat = "identity", fill = "cornflowerblue") +

  geom_text(data = evlilik_bosanma_hiz,
            aes(x = Yil, y = Evlenme_Sayisi,
                label = format(Evlenme_Sayisi)),
            angle = 90, vjust = 0.5, hjust = 3,
            color = "white", size = 4) +

#Çizgi ve nokta grafiği çizelim

  geom_line(data = hizlar,
            aes(x = Yil, y = Y_Pos, color = Kaba_Evlenme_Hizi, group = Kaba_Evlenme_Hizi),
            size = 1.2) +
  geom_point(data = hizlar,
             aes(x = Yil, y = Y_Pos, color = Kaba_Evlenme_Hizi),
             size = 2.5) +
  geom_text(data = hizlar,
            aes(x = Yil, y = Y_Pos, label = Etiket, color = Kaba_Evlenme_Hizi),
            vjust = -1, size = 3, show.legend = FALSE) +

  scale_color_manual(values = c("Kaba evlenme hızı" = "darkred")) +

# Ekseni ayarla
  scale_y_continuous(
    name = "Evlenme sayısı",
    sec.axis = sec_axis(~./80000, name = "Kaba hız (Binde)")
  ) +
  scale_x_continuous(breaks = evlilik_bosanma_hiz$Yil) +

  # Etiketler ve tema
  labs(
    title = "Yıllara Göre Evlenme Sayısı ve Kaba Evlenme Hızı",
    x = "Yıl",
    color = "Gösterge"  # sadece çizgi için legend başlığı
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    axis.title.y = element_text(color = "black", size = 12),
    axis.title.y.right = element_text(color = "black", size = 12),
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )
# Sonuçları göster


#boşanma nüfus grafiği

library(readxl)
library(dplyr)
library(ggplot2)
library(tidyr)

# Veriyi oku
evlilik_bosanma_hiz <- read_excel("veri/evlilik-bosanma-nufus.xls")

# Kaba evlenme hızı hesapla
evlilik_bosanma_hiz <- evlilik_bosanma_hiz %>%
  mutate(
    Yil = as.numeric(Yil),
    Kaba_Bosanma_Hizi = (Bosanma_Sayisi / Nufus_Sayisi) * 1000
  )

# Çizgi verisi hazırlığı
hizlar <- evlilik_bosanma_hiz %>%
  select(Yil, Kaba_Bosanma_Hizi) %>%
  pivot_longer(cols = Kaba_Bosanma_Hizi, names_to = "Kaba_Bosanma_Hizi", values_to = "Deger") %>%
  mutate(
    Kaba_Bosanma_Hizi = "Kaba bosanma hızı",
    Etiket = paste0(format(round(Deger, 2), nsmall = 2), " "),
    Y_Pos = Deger * 80000
  )

# Barplot çizelim
ggplot() +
  geom_bar(data = evlilik_bosanma_hiz,
           aes(x = Yil, y = Bosanma_Sayisi),
           stat = "identity", fill = "pink") +

  geom_text(data = evlilik_bosanma_hiz,
            aes(x = Yil, y = Bosanma_Sayisi,
                label = format(Bosanma_Sayisi)),
            angle = 90, vjust = 0.5, hjust = 3,
            color = "black",size = 4) +

#Çizgi ve nokta grafiği çizelim

  geom_line(data = hizlar,
            aes(x = Yil, y = Y_Pos, color = Kaba_Bosanma_Hizi, group = Kaba_Bosanma_Hizi),
            size = 1.2) +
  geom_point(data = hizlar,
             aes(x = Yil, y = Y_Pos, color = Kaba_Bosanma_Hizi),
             size = 2.5) +
  geom_text(data = hizlar,
            aes(x = Yil, y = Y_Pos, label = Etiket, color = Kaba_Bosanma_Hizi),
            vjust = -1, size = 3, show.legend = FALSE) +

  scale_color_manual(values = c("Kaba bosanma hızı" = "purple")) +

# Ekseni ayarla
  scale_y_continuous(
    name = "Bosanma sayısı",
    sec.axis = sec_axis(~./80000, name = "Kaba hız (Binde)")
  ) +
  scale_x_continuous(breaks = evlilik_bosanma_hiz$Yil) +

  # Etiketler ve tema
  labs(
    title = "Yıllara Göre Bosanma Sayısı ve Kaba Bosanma Hızı",
    x = "Yıl",
    color = "Black"  
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    axis.title.y = element_text(color = "black", size = 12),
    axis.title.y.right = element_text(color = "black", size = 12),
    plot.title = element_text(hjust = 0.5, size = 14, face = "bold")
  )

## Sonuçlar

xxxxxx

# Sonuçlar ve Ana Çıkarımlar

xxxxxx
