---
title: "Çalışma 1"
editor: 
  markdown: 
    wrap: 72
---

install.packages("dslabs")

library(dslabs)

A. VİDEO ÖZETİ

B. FONKSİYONLAR VE DÖNGÜLER İLE VERİLERİ ÖZETLEME

-   Özel Özet Fonksiyonu Yazın:

```{r}



data(mtcars)

class(mtcars)

## Veri Seti İnceleme

head(mtcars)

str(mtcars)

print(mtcars)

my_summary_stats <- function(vec) {

total_list <- list( ortalama = mean(vec),

medyan = median(vec),

standart_sapma = sd(vec),

minimum = min(vec),

maksimum = max(vec) )
} #değerleri yazdırma

sonuc <- my_summary_stats(mtcars$mpg) 
print(sonuc)
```

-   Fonksiyonu Döngü Kullanarak Uygulama:

```{r}

dongu <- list()  # dongu'yu boş bir liste olarak başlatıyoruz

for(x in 1:11) {
 
  dongu[[x]] <- my_summary_stats(mtcars[[x]])  # Özet istatistikleri hesaplayıp listeye ekliyoruz
  
cat("\n=====", colnames(mtcars)[x], "====\n")

cat(paste(names(dongu[[x]]),dongu[[x]],sep =":" , collapse = " | "),"\n")# Özet istatistiklerini , istatistiklerin ismi ile birlikte yazdırıyoruz

}
```

-   Apply ile Alternatif Bir Yaklaşım:

```{r}

cat("\n=== Ortalama ===\n",paste(colnames(mtcars), apply(mtcars, 2, mean), sep = ": ", collapse = " | "), "\n")

cat("\n=== Standart Sapma ===\n",paste(colnames(mtcars), apply(mtcars, 2, sd), sep = ": ", collapse = " | "), "\n")

cat("\n=== Medyan ===\n",paste(colnames(mtcars), apply(mtcars, 2, median), sep = ": ", collapse = " | "), "\n")

cat("\n=== Minimum  ===\n",paste(colnames(mtcars), apply(mtcars, 2, min), sep = ": ", collapse = " | "), "\n")

cat("\n=== Maksimum ===\n",paste(colnames(mtcars), apply(mtcars, 2, max), sep = ": ", collapse = " | "), "\n")

```

C. SORUSUNUN CEVABI

<<<<<<< HEAD
```{r}
data("na_example")
na_sayisi <- sum(is.na(na_example))
cat("Veri setinde", na_sayisi, "adet eksik (NA) değer bulunmaktadır.\n")












```
=======
install.packages("dslabs")

library(dslabs)

data(na_example)
```{r}


sum(is.na(na_example))

change_na <- ifelse(is.na(na_example),2025,na_example)

print(change_na)

```
>>>>>>> 8f1af22b4106534afbc679db49f0166d37e0381d
